/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dav(props) {
  const { nodes, materials } = useGLTF("/tarta1.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials.BODY1_ARD_front}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials.BODY1_ARD_front}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tarta-peq_ARD-geom"].geometry}
        material={materials["tarta-peq_ARD_front"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tarta-peq_ARD-geom_1"].geometry}
        material={materials["tarta-peq_ARD_back"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tarta-peq_ARD-geom_2"].geometry}
        material={materials["tarta-peq_ARD_edge"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tarta-big_ARD-geom"].geometry}
        material={materials["tarta-big_ARD_front"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tarta-big_ARD-geom_1"].geometry}
        material={materials["tarta-big_ARD_back"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tarta-big_ARD-geom_2"].geometry}
        material={materials["tarta-big_ARD_edge"]}
      />
    </group>
  );
}

useGLTF.preload("/tarta1.gltf");
